version: "3.4"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      KAFKA_TOPIC: san_exporter_test
    ports:
      # port for checking health.
      - "127.0.0.1:3000:3000"
    entrypoint: "/bin/sh"
    command: ["-c", "docker/wait_for_services.sh && node examples/send_dates.js && node examples/send_dates_transaction.js"]
